import { LocalHospital, LocalPharmacy, Science } from "@mui/icons-material";
import {
  Package,
  Clock,
  CheckCircle,
  XCircle,
  ShoppingBag,
  MapPin,
  Calendar,
  Pill,
  ChevronRight,
  Filter,
} from "lucide-react";

export const mockUsers = {
  patient: {
    name: "Sarah Johnson",
    email: "sarah.johnson@email.com",
    phone: "+1 (555) 123-4567",
    location: "New York, NY",
    role: "Patient",
    memberSince: "January 2024",
  },
  doctor: {
    name: "Dr. Michael Chen",
    email: "m.chen@clinic.com",
    phone: "+1 (555) 987-6543",
    location: "Los Angeles, CA",
    role: "Doctor",
    memberSince: "March 2023",
  },
  pharmacist: {
    name: "Emily Rodriguez",
    email: "e.rodriguez@pharmacy.com",
    phone: "+1 (555) 456-7890",
    location: "Chicago, IL",
    role: "Pharmacist",
    memberSince: "June 2023",
  },
  lab_technician: {
    name: "James Wilson",
    email: "j.wilson@lab.com",
    phone: "+1 (555) 321-0987",
    location: "Houston, TX",
    role: "Lab Technician",
    memberSince: "September 2023",
  },
};

export const pharmacies = [
  {
    id: "p1",
    name: "MediCare Pharmacy",
    specialty: "General Pharmacy",
    avatar:
      "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=200&h=200&fit=crop",
    rating: 4.8,
    reviewCount: 234,
    experience: "Open 24/7",
    location: "123 Health Street",
    available: true,
    nextAvailable: "Open Now",
  },
  {
    id: "p2",
    name: "HealthPlus Pharmacy",
    specialty: "Specialty Medications",
    avatar:
      "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=200&h=200&fit=crop",
    rating: 4.6,
    reviewCount: 189,
    experience: "Since 2010",
    location: "456 Wellness Ave",
    available: true,
    nextAvailable: "Open Now",
  },
  {
    id: "p3",
    name: "Community Drugs",
    specialty: "Compounding",
    avatar:
      "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 156,
    experience: "Family owned",
    location: "789 Care Blvd",
    available: false,
    nextAvailable: "Opens 8:00 AM",
  },
];

export const labs = [
  {
    id: "35",
    name: "DiagnoLab Central",
    specialty: "Blood Work",
    avatar:
      "https://images.unsplash.com/photo-1579154204601-01588f351e67?w=200&h=200&fit=crop",
    rating: 4.9,
    reviewCount: 312,
    experience: "ISO Certified",
    location: "Medical Center, Floor 2",
    available: true,
    nextAvailable: "Today, 10:00 AM",
  },
  {
    id: "l2",
    name: "PathCare Labs",
    specialty: "Pathology",
    avatar:
      "https://images.unsplash.com/photo-1582719471384-894fbb16e074?w=200&h=200&fit=crop",
    rating: 4.7,
    reviewCount: 198,
    experience: "20+ years",
    location: "Building B, Room 105",
    available: true,
    nextAvailable: "Today, 2:30 PM",
  },
  {
    id: "l3",
    name: "QuickTest Labs",
    specialty: "Rapid Testing",
    avatar:
      "https://images.unsplash.com/photo-1576671081837-49000212a370?w=200&h=200&fit=crop",
    rating: 4.5,
    reviewCount: 267,
    experience: "Fast results",
    location: "Main Street Clinic ",
    available: false,
    nextAvailable: "Tomorrow, 9:00 AM",
  },
];

export const doctors = [
  {
    id: "1",
    name: "Dr. Sarah Johnson",
    specialty: "Cardiology",
    avatar:
      "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=200&h=200&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 127,
    experience: "15 years exp.",
    location: "Building A, Room 102",
    available: true,
    nextAvailable: "Today, 2:00 PM",
  },
  {
    id: "2",
    name: "Dr. Michael Chen",
    specialty: "Neurology",
    avatar:
      "https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=200&h=200&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 98,
    experience: "12 years exp.",
    location: "Building B, Room 205",
    available: true,
    nextAvailable: "Tomorrow, 9:00 AM",
  },
  {
    id: "3",
    name: "Dr. Emily Roberts",
    specialty: "Dermatology",
    avatar:
      "https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=200&h=200&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 156,
    experience: "8 years exp.",
    location: "Building A, Room 301",
    available: false,
    nextAvailable: "Dec 12, 10:00 AM",
  },
  {
    id: "4",
    name: "Dr. James Wilson",
    specialty: "Orthopedics",
    avatar:
      "https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=200&h=200&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 203,
    experience: "20 years exp.",
    location: "Building C, Room 101",
    available: true,
    nextAvailable: "Today, 4:30 PM",
  },
  {
    id: "5",
    name: "Dr. Lisa Anderson",
    specialty: "Pediatrics",
    avatar:
      "https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=200&h=200&fit=crop&crop=face",
    rating: 4.8,
    reviewCount: 89,
    experience: "10 years exp.",
    location: "Building B, Room 110",
    available: true,
    nextAvailable: "Today, 3:15 PM",
  },
  {
    id: "6",
    name: "Dr. Robert Martinez",
    specialty: "General Medicine",
    avatar:
      "https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=200&h=200&fit=crop&crop=face",
    rating: 4.6,
    reviewCount: 178,
    experience: "18 years exp.",
    location: "Building A, Room 105",
    available: false,
    nextAvailable: "Dec 13, 11:00 AM",
  },
  {
    id: "7",
    name: "Dr. Jennifer Lee",
    specialty: "Psychiatry",
    avatar:
      "https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=200&h=200&fit=crop&crop=face",
    rating: 4.9,
    reviewCount: 112,
    experience: "14 years exp.",
    location: "Building D, Room 201",
    available: true,
    nextAvailable: "Tomorrow, 2:00 PM",
  },
  {
    id: "8",
    name: "Dr. David Thompson",
    specialty: "Ophthalmology",
    avatar:
      "https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=200&h=200&fit=crop&crop=face",
    rating: 4.7,
    reviewCount: 145,
    experience: "16 years exp.",
    location: "Building C, Room 302",
    available: true,
    nextAvailable: "Today, 5:00 PM",
  },
];

export const specialtiesMap = {
  doctors: [
    "Cardiology",
    "Dermatology",
    "Neurology",
    "Orthopedics",
    "Pediatrics",
    "General Medicine",
    "Psychiatry",
    "Ophthalmology",
  ],
  pharmacies: ["General Pharmacy", "Specialty Medications", "Compounding"],
  labs: ["Blood Work", "Pathology", "Rapid Testing"],
};

export const userTypeLabels = {
  doctors: { singular: "doctor", plural: "doctors", icon: LocalHospital },
  pharmacies: {
    singular: "pharmacy",
    plural: "pharmacies",
    icon: LocalPharmacy,
  },
  labs: { singular: "lab", plural: "labs", icon: Science },
};

export const labTests = [
  {
    id: "1",
    name: "Complete Blood Count (CBC)",
    category: "Hematology",
    orderedBy: "Dr. Sarah Johnson",
    orderedDate: "2024-12-05",
    resultDate: "2024-12-07",
    status: "completed",
    results: [
      {
        name: "White Blood Cells",
        value: "7.5",
        unit: "K/uL",
        reference: "4.5-11.0",
        status: "low",
      },
      {
        name: "Red Blood Cells",
        value: "4.8",
        unit: "M/uL",
        reference: "4.5-5.5",
        status: "normal",
      },
      {
        name: "Hemoglobin",
        value: "14.2",
        unit: "g/dL",
        reference: "13.5-17.5",
        status: "normal",
      },
      {
        name: "Platelets",
        value: "180",
        unit: "K/uL",
        reference: "150-400",
        status: "normal",
      },
    ],
  },
  {
    id: "2",
    name: "Lipid Panel",
    category: "Chemistry",
    orderedBy: "Dr. Michael Chen",
    orderedDate: "2024-12-08",
    resultDate: "2024-12-10",
    status: "completed",
    results: [
      {
        name: "Total Cholesterol",
        value: "220",
        unit: "mg/dL",
        reference: "<200",
        status: "high",
      },
      {
        name: "LDL Cholesterol",
        value: "145",
        unit: "mg/dL",
        reference: "<100",
        status: "high",
      },
      {
        name: "HDL Cholesterol",
        value: "55",
        unit: "mg/dL",
        reference: ">40",
        status: "normal",
      },
      {
        name: "Triglycerides",
        value: "120",
        unit: "mg/dL",
        reference: "<150",
        status: "normal",
      },
    ],
  },
  {
    id: "3",
    name: "Thyroid Function Panel",
    category: "Endocrinology",
    orderedBy: "Dr. Emily Rodriguez",
    orderedDate: "2024-12-10",
    resultDate: null,
    status: "in-progress",
    results: null,
    priority: "Urgent",
  },
  {
    id: "4",
    name: "Urinalysis",
    category: "Urinalysis",
    orderedBy: "Dr. Sarah Johnson",
    orderedDate: "2024-12-11",
    resultDate: null,
    status: "pending",
    results: null,
  },
];

export const prescriptions = [
  {
    id: "1",
    prescriptionNumber: "RX-2024-001547",
    medications: [
      {
        name: "Lisinopril",
        dosage: "10mg",
        frequency: "Once daily",
        instructions: "Take in the morning with water",
      },
      {
        name: "Amlodipine",
        dosage: "5mg",
        frequency: "Once daily",
        instructions: "Take with or without food",
      },
      {
        name: "Hydrochlorothiazide",
        dosage: "25mg",
        frequency: "Once daily in morning",
        instructions: "Take early in day to avoid nighttime urination",
      },
    ],
    prescribedBy: "Dr. Sarah Johnson",
    prescribedDate: "2024-11-15",
    expiryDate: "2025-05-15",
    status: "active",
    refillsRemaining: 3,
    doctorId: "1",
    diagnosis: "Hypertension Management",
  },
  {
    id: "2",
    prescriptionNumber: "RX-2024-001398",
    medications: [
      {
        name: "Metformin",
        dosage: "500mg",
        frequency: "Twice daily",
        instructions: "Take with meals to reduce stomach upset",
      },
      {
        name: "Glipizide",
        dosage: "5mg",
        frequency: "Once daily before breakfast",
        instructions: "Take 30 minutes before first meal",
      },
    ],
    prescribedBy: "Dr. Michael Chen",
    prescribedDate: "2024-10-20",
    expiryDate: "2025-04-20",
    status: "active",
    refillsRemaining: 0,
    doctorId: "2",
    diagnosis: "Type 2 Diabetes",
  },
  {
    id: "3",
    prescriptionNumber: "RX-2024-000982",
    medications: [
      {
        name: "Atorvastatin",
        dosage: "20mg",
        frequency: "Once daily at bedtime",
        instructions: "Take at bedtime. Avoid grapefruit juice",
      },
    ],
    prescribedBy: "Dr. Sarah Johnson",
    prescribedDate: "2024-08-10",
    expiryDate: "2024-11-10",
    status: "expired",
    refillsRemaining: 0,
    doctorId: "3",
    diagnosis: "Hypercholesterolemia",
  },
  {
    id: "4",
    prescriptionNumber: "RX-2024-001621",
    medications: [
      {
        name: "Omeprazole",
        dosage: "20mg",
        frequency: "Once daily before breakfast",
        instructions: "Take 30 minutes before eating. Do not crush or chew",
      },
      {
        name: "Sucralfate",
        dosage: "1g",
        frequency: "Four times daily",
        instructions: "Take on empty stomach, 1 hour before meals",
      },
      {
        name: "Famotidine",
        dosage: "20mg",
        frequency: "Twice daily",
        instructions: "Take morning and evening",
      },
    ],
    prescribedBy: "Dr. Emily Rodriguez",
    prescribedDate: "2024-12-01",
    expiryDate: "2025-06-01",
    status: "active",
    refillsRemaining: 5,
    doctorId: "4",
    diagnosis: "GERD & Peptic Ulcer",
  },
];

export const mockMedications = [
  {
    id: "1",
    name: "Ibuprofen 200mg",
    description: "Pain relief and anti-inflammatory",
    price: 8.99,
    category: "Pain Relief",
    requiresPrescription: false,
    inStock: true,
  },
  {
    id: "2",
    name: "Vitamin D3 1000IU",
    description: "Supports bone health and immunity",
    price: 12.49,
    category: "Vitamins",
    requiresPrescription: false,
    inStock: true,
  },
  {
    id: "3",
    name: "Cetirizine 10mg",
    description: "24-hour allergy relief",
    price: 15.99,
    category: "Allergy",
    requiresPrescription: false,
    inStock: true,
  },
  {
    id: "4",
    name: "Omega-3 Fish Oil",
    description: "Heart and brain health support",
    price: 24.99,
    category: "Supplements",
    requiresPrescription: false,
    inStock: true,
  },
  {
    id: "5",
    name: "Acetaminophen 500mg",
    description: "Fever reducer and pain reliever",
    price: 6.99,
    category: "Pain Relief",
    requiresPrescription: false,
    inStock: false,
  },
  {
    id: "6",
    name: "Multivitamin Daily",
    description: "Complete daily nutrition",
    price: 18.99,
    category: "Vitamins",
    requiresPrescription: false,
    inStock: true,
  },
];

export const mockConversations = [
  {
    id: "1",
    pharmacyId: "p1",
    Name: "HealthCare Pharmacy",
    Avatar:
      "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=200&h=200&fit=crop",
    lastMessage: "Your prescription is ready for pickup!",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
    unreadCount: 1,
    messages: [
      {
        id: "1",
        senderId: "pharmacy",
        content: "Hello! How can we help you today?",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
        isRead: true,
      },
      {
        id: "2",
        senderId: "user",
        content: "Hi, I need to refill my Lisinopril prescription.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60),
        isRead: true,
      },
      {
        id: "3",
        senderId: "pharmacy",
        content: "Your prescription is ready for pickup!",
        timestamp: new Date(Date.now() - 1000 * 60 * 30),
        isRead: false,
      },
    ],
  },
  {
    id: "2",
    pharmacyId: "p2",
    Name: "MedPlus Drugstore",
    Avatar:
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=200&h=200&fit=crop",
    lastMessage: "Thank you for your order!",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 24),
    unreadCount: 0,
    messages: [
      {
        id: "1",
        senderId: "user",
        content: "Do you have Vitamin D in stock?",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25),
        isRead: true,
      },
      {
        id: "2",
        senderId: "pharmacy",
        content: "Thank you for your order!",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
        isRead: true,
      },
    ],
  },
  {
    id: "4",
    labId: "l1",
    Name: "DiagnoLab Central",
    Avatar:
      "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=200&h=200&fit=crop",
    lastMessage: "Lab Results Are Ready!",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
    unreadCount: 1,
    messages: [
      {
        id: "1",
        senderId: "pharmacy",
        content: "Hello! How can we help you today?",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
        isRead: true,
      },
      {
        id: "2",
        senderId: "user",
        content: "Hi, I need to refill my Lisinopril prescription.",
        timestamp: new Date(Date.now() - 1000 * 60 * 60),
        isRead: true,
      },
      {
        id: "3",
        senderId: "pharmacy",
        content: "Your prescription is ready for pickup!",
        timestamp: new Date(Date.now() - 1000 * 60 * 30),
        isRead: false,
      },
    ],
  },
  // {
  //     id: '88',
  //     doctorId: '1',
  //     Name: 'Dr Ahmed',
  //     Avatar: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=200&h=200&fit=crop',
  //     lastMessage: 'Your prescription is ready for pickup!',
  //     lastMessageTime: new Date(Date.now() - 1000 * 60 * 30),
  //     unreadCount: 1,
  //     messages: [
  //         {
  //             id: '1',
  //             senderId: 'pharmacy',
  //             content: 'Hello! How can we help you today?',
  //             timestamp: new Date(Date.now() - 1000 * 60 * 60 * 2),
  //             isRead: true,
  //         },
  //         {
  //             id: '2',
  //             senderId: 'user',
  //             content: 'Hi, I need to refill my Lisinopril prescription.',
  //             timestamp: new Date(Date.now() - 1000 * 60 * 60),
  //             isRead: true,
  //         },
  //         {
  //             id: '3',
  //             senderId: 'pharmacy',
  //             content: 'Your prescription is ready for pickup!',
  //             timestamp: new Date(Date.now() - 1000 * 60 * 30),
  //             isRead: false,
  //         },
  //     ],
  // },
  {
    id: "99",
    doctorId: "2",
    Name: "Dr Mohamed",
    Avatar:
      "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=200&h=200&fit=crop",
    lastMessage: "Thank you for your order!",
    lastMessageTime: new Date(Date.now() - 1000 * 60 * 60 * 24),
    unreadCount: 0,
    messages: [
      {
        id: "1",
        senderId: "user",
        content: "Do you have Vitamin D in stock?",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 25),
        isRead: true,
      },
      {
        id: "2",
        senderId: "pharmacy",
        content: "Thank you for your order!",
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
        isRead: true,
      },
    ],
  },
];

export const mockMedicalRecords = [
  {
    id: "1",
    appointmentDate: "2024-01-15",
    doctorName: "Dr. Sarah Johnson",
    specialty: "General Practice",
    diagnosis: "Upper Respiratory Infection",
    symptoms: ["Cough", "Sore throat", "Nasal congestion", "Mild fever"],
    medications: [
      {
        name: "Amoxicillin 500mg",
        dosage: "1 tablet 3 times daily",
        duration: "7 days",
      },
      {
        name: "Ibuprofen 400mg",
        dosage: "1 tablet as needed",
        duration: "For pain/fever",
      },
    ],
    labTests: [
      { name: "Complete Blood Count", result: "Normal", date: "2024-01-15" },
      {
        name: "Throat Culture",
        result: "Negative for strep",
        date: "2024-01-15",
      },
    ],
    recoveryPlan:
      "Rest for 3-5 days, increase fluid intake, follow up if symptoms worsen or persist beyond 7 days.",
    notes: "Patient advised to avoid cold beverages and get adequate sleep.",
    status: "completed",
  },
  {
    id: "2",
    appointmentDate: "2024-01-28",
    doctorName: "Dr. Michael Chen",
    specialty: "Cardiology",
    diagnosis: "Mild Hypertension",
    symptoms: ["Elevated blood pressure", "Occasional headaches", "Fatigue"],
    medications: [
      {
        name: "Lisinopril 10mg",
        dosage: "1 tablet daily in the morning",
        duration: "Ongoing",
      },
    ],
    labTests: [
      {
        name: "Lipid Panel",
        result: "Cholesterol slightly elevated",
        date: "2024-01-28",
      },
      {
        name: "Basic Metabolic Panel",
        result: "Normal kidney function",
        date: "2024-01-28",
      },
      { name: "ECG", result: "Normal sinus rhythm", date: "2024-01-28" },
    ],
    recoveryPlan:
      "Lifestyle modifications including reduced sodium intake, regular exercise 30 minutes daily, stress management. Follow up in 4 weeks to monitor blood pressure.",
    notes:
      "Patient encouraged to monitor blood pressure at home and maintain a log.",
    status: "ongoing",
  },
  {
    id: "3",
    appointmentDate: "2024-02-10",
    doctorName: "Dr. Emily Rodriguez",
    specialty: "Orthopedics",
    diagnosis: "Lumbar Strain",
    symptoms: [
      "Lower back pain",
      "Muscle stiffness",
      "Limited range of motion",
    ],
    medications: [
      {
        name: "Cyclobenzaprine 10mg",
        dosage: "1 tablet at bedtime",
        duration: "10 days",
      },
      {
        name: "Naproxen 500mg",
        dosage: "1 tablet twice daily with food",
        duration: "14 days",
      },
    ],
    labTests: [
      {
        name: "X-Ray Lumbar Spine",
        result: "No fractures, mild disc degeneration",
        date: "2024-02-10",
      },
    ],
    recoveryPlan:
      "Physical therapy 2x weekly for 4 weeks, apply heat/ice as needed, avoid heavy lifting. Gradual return to normal activities.",
    notes:
      "Referred to physical therapy. Ergonomic assessment recommended for workstation.",
    status: "in-progress",
  },
];

export const availableTests = [
  {
    id: 1,
    name: "Complete Blood Count (CBC)",
    description:
      "Measures different components of your blood including red cells, white cells, and platelets",
    price: 45.0,
    turnaroundTime: "24-48 hours",
    available: true,
  },
  {
    id: 2,
    name: "Lipid Panel",
    description:
      "Checks cholesterol levels including HDL, LDL, and triglycerides",
    price: 65.0,
    turnaroundTime: "1-2 days",
    available: true,
  },
  {
    id: 3,
    name: "Thyroid Stimulating Hormone (TSH)",
    description: "Evaluates thyroid function and metabolism regulation",
    price: 55.0,
    turnaroundTime: "2-3 days",
    available: true,
  },
  {
    id: 4,
    name: "Comprehensive Metabolic Panel",
    description: "Tests kidney function, blood sugar, and electrolyte balance",
    price: 75.0,
    turnaroundTime: "24 hours",
    available: true,
  },
  {
    id: 5,
    name: "Vitamin D Test",
    description: "Measures vitamin D levels to assess bone health and immunity",
    price: 50.0,
    turnaroundTime: "3-5 days",
    available: false,
  },
  {
    id: 6,
    name: "Hemoglobin A1C",
    description: "Monitors average blood sugar levels over the past 3 months",
    price: 40.0,
    turnaroundTime: "1-2 days",
    available: true,
  },
  {
    id: 7,
    name: "Liver Function Panel",
    description: "Assesses liver health and detects liver damage or disease",
    price: 70.0,
    turnaroundTime: "2-3 days",
    available: true,
  },
  {
    id: 8,
    name: "COVID-19 PCR Test",
    description: "Detects active coronavirus infection with high accuracy",
    price: 85.0,
    turnaroundTime: "12-24 hours",
    available: true,
  },
  {
    id: 9,
    name: "Iron Panel",
    description: "Checks iron levels, ferritin, and iron binding capacity",
    price: 60.0,
    turnaroundTime: "2-4 days",
    available: false,
  },
  {
    id: 10,
    name: "Urinalysis",
    description: "Screens for urinary tract infections and kidney problems",
    price: 30.0,
    turnaroundTime: "24 hours",
    available: true,
  },
];

export const mockOrders = [
  {
    id: "ORD-001",
    pharmacy: {
      name: "HealthCare Pharmacy",
      location: "Building A, Ground Floor",
      avatar:
        "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=100&h=100&fit=crop",
    },
    items: [
      { name: "Amoxicillin 500mg", quantity: 2, dosage: "3x daily" },
      { name: "Ibuprofen 400mg", quantity: 1, dosage: "As needed" },
    ],
    status: "ready",
    orderDate: "2024-12-12",
    readyDate: "2024-12-13",
    total: 45.99,
    prescriptionId: "RX-12345",
  },
  {
    id: "ORD-002",
    pharmacy: {
      name: "MedPlus Drugstore",
      location: "Building B, First Floor",
      avatar:
        "https://images.unsplash.com/photo-1585435557343-3b092031a831?w=100&h=100&fit=crop",
    },
    items: [{ name: "Metformin 850mg", quantity: 1, dosage: "2x daily" }],
    status: "pending",
    orderDate: "2024-12-13",
    estimatedReady: "2024-12-14",
    total: 28.5,
    prescriptionId: "RX-12346",
  },
  {
    id: "ORD-003",
    pharmacy: {
      name: "City Pharmacy",
      location: "Building C, Second Floor",
      avatar:
        "https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=100&h=100&fit=crop",
    },
    items: [
      { name: "Vitamin D3 1000IU", quantity: 1, dosage: "1x daily" },
      { name: "Omega-3 Fish Oil", quantity: 1, dosage: "2x daily" },
      { name: "Multivitamin Complex", quantity: 1, dosage: "1x daily" },
    ],
    status: "taken",
    orderDate: "2024-12-10",
    pickedUpDate: "2024-12-11",
    total: 67.25,
    prescriptionId: null,
  },
  {
    id: "ORD-004",
    pharmacy: {
      name: "HealthCare Pharmacy",
      location: "Building A, Ground Floor",
      avatar:
        "https://images.unsplash.com/photo-1576602976047-174e57a47881?w=100&h=100&fit=crop",
    },
    items: [{ name: "Aspirin 100mg", quantity: 1, dosage: "1x daily" }],
    status: "cancelled",
    orderDate: "2024-12-08",
    cancelledDate: "2024-12-09",
    cancelReason: "Item out of stock",
    total: 12.0,
    prescriptionId: "RX-12340",
  },
  {
    id: "ORD-005",
    pharmacy: {
      name: "QuickMeds Pharmacy",
      location: "Building D, Ground Floor",
      avatar:
        "https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=100&h=100&fit=crop",
    },
    items: [
      { name: "Lisinopril 10mg", quantity: 1, dosage: "1x daily" },
      { name: "Atorvastatin 20mg", quantity: 1, dosage: "1x at night" },
    ],
    status: "ready",
    orderDate: "2024-12-11",
    readyDate: "2024-12-12",
    total: 52.75,
    prescriptionId: "RX-12344",
  },
];

export const statusConfig = {
  requested: {
    label: "Pending",
    color: "#f59e0b",
    bgColor: "rgba(245, 158, 11, 0.1)",
    icon: Clock,
  },
  ready_for_pickup: {
    label: "Ready for Pickup",
    color: "#10b981",
    bgColor: "rgba(16, 185, 129, 0.1)",
    icon: CheckCircle,
  },
  completed: {
    label: "Picked Up",
    color: "#6366f1",
    bgColor: "rgba(99, 102, 241, 0.1)",
    icon: Package,
  },
  cancelled: {
    label: "Cancelled",
    color: "#ef4444",
    bgColor: "rgba(239, 68, 68, 0.1)",
    icon: XCircle,
  },
};

export const appointments = [
  {
    id: "apt-1",
    doctorName: "Dr. Sarah Johnson",
    doctorid: 1,
    doctorSpecialty: "Cardiologist",
    date: "2024-12-20",
    startTime: "09:00",
    fees: 150,
    status: "upcoming",
  },
  {
    id: "apt-2",
    doctorName: "Dr. Michael Chen",
    doctorid: 2,
    doctorSpecialty: "Endocrinologist",
    date: "2024-12-22",
    startTime: "14:30",
    fees: 175,
    status: "upcoming",
  },
  {
    id: "apt-3",
    doctorName: "Dr. Sarah Johnson",
    doctorid: 1,
    doctorSpecialty: "Cardiologist",
    date: "2024-11-15",
    startTime: "10:00",
    fees: 150,
    status: "completed",
    prescriptionId: "1",
    labTestIds: ["1"],
  },
  {
    id: "apt-4",
    doctorName: "Dr. Michael Chen",
    doctorid: 1,
    doctorSpecialty: "Endocrinologist",
    date: "2024-10-20",
    startTime: "11:30",
    fees: 175,
    status: "completed",
    prescriptionId: "2",
    labTestIds: ["2"],
  },
  {
    id: "apt-5",
    doctorName: "Dr. Emily Rodriguez",
    doctorid: 3,
    doctorSpecialty: "Gastroenterologist",
    date: "2024-12-01",
    startTime: "15:00",
    fees: 200,
    status: "completed",
    prescriptionId: "4",
    labTestIds: ["3"],
  },
  {
    id: "apt-6",
    doctorName: "Dr. James Wilson",
    doctorid: 3,
    doctorSpecialty: "General Physician",
    date: "2024-11-28",
    startTime: "09:30",
    fees: 100,
    status: "cancelled",
  },
  {
    id: "apt-7",
    doctorName: "Dr. Lisa Park",
    doctorid: 2,
    doctorSpecialty: "Dermatologist",
    date: "2024-11-10",
    startTime: "16:00",
    fees: 125,
    status: "cancelled",
  },
];

export const recentActivities = [
  {
    id: 1,
    action: "New patient registered",
    user: "John Doe",
    time: "2 minutes ago",
    type: "patient",
  },
  {
    id: 2,
    action: "Doctor account approved",
    user: "Dr. Sarah Wilson",
    time: "15 minutes ago",
    type: "doctor",
  },
  {
    id: 3,
    action: "New medication added",
    user: "Amoxicillin 500mg",
    time: "1 hour ago",
    type: "medication",
  },
  {
    id: 4,
    action: "Lab exam updated",
    user: "Complete Blood Count",
    time: "2 hours ago",
    type: "lab",
  },
  {
    id: 5,
    action: "User account deleted",
    user: "Mark Johnson",
    time: "3 hours ago",
    type: "user",
  },
];

export const systemStats = [
  { label: "Server Uptime", value: 99.9, color: "hsl(var(--success))" },
  { label: "Database Usage", value: 45, color: "hsl(var(--primary))" },
  { label: "API Response Time", value: 82, color: "hsl(var(--accent))" },
  { label: "Storage Used", value: 67, color: "hsl(var(--warning))" },
];

export const changeColors = {
  positive: "text-success",
  negative: "text-destructive",
  neutral: "text-muted-foreground",
};

export const mockAdmins = [
  {
    id: "1",
    name: "Super Admin",
    email: "admin@medisystem.com",
    createdAt: "2023-01-01",
    lastLogin: "2024-03-20 14:30",
    phone: "010000",
  },
  {
    id: "2",
    name: "Jane Smith",
    email: "jane.smith@medisystem.com",
    createdAt: "2024-01-10",
    lastLogin: "2024-03-19 09:15",
    phone: "010000",
  },
  {
    id: "3",
    name: "Robert Johnson",
    email: "robert.j@medisystem.com",
    createdAt: "2024-02-15",
    lastLogin: "2024-03-18 16:45",
    phone: "010000",
  },
];

export const mockLabExams = [
  {
    id: "1",
    test_name: "Complete Blood Count (CBC)",
    category: "Hematology",
    preparation_notes: "No fasting required",
    warnings: "None",
    price: 45.0,
    duration: "1-2 hours",
  },
  {
    id: "2",
    test_name: "Lipid Panel",
    category: "Chemistry",
    preparation_notes: "Fasting 9-12 hours",
    warnings: "Avoid fatty foods",
    price: 65.0,
    duration: "24 hours",
  },
  {
    id: "3",
    test_name: "Liver Function Test",
    category: "Chemistry",
    preparation_notes: "Fasting 8-12 hours",
    warnings: "Avoid alcohol 24h before",
    price: 55.0,
    duration: "24 hours",
  },
  {
    id: "4",
    test_name: "Thyroid Panel",
    category: "Endocrinology",
    preparation_notes: "No preparation needed",
    warnings: "Inform about medications",
    price: 85.0,
    duration: "2-3 days",
  },
  {
    id: "5",
    test_name: "Urinalysis",
    category: "Microbiology",
    preparation_notes: "Clean-catch sample",
    warnings: "Avoid contamination",
    price: 25.0,
    duration: "1-2 hours",
  },
  {
    id: "6",
    test_name: "HbA1c",
    category: "Chemistry",
    preparation_notes: "No fasting required",
    warnings: "For diabetes monitoring",
    price: 40.0,
    duration: "24 hours",
  },
  {
    id: "7",
    test_name: "Vitamin D Test",
    category: "Chemistry",
    preparation_notes: "No preparation needed",
    warnings: "None",
    price: 75.0,
    duration: "2-3 days",
  },
  {
    id: "8",
    test_name: "COVID-19 PCR",
    category: "Molecular",
    preparation_notes: "Nasal swab required",
    warnings: "Results in 24-48h",
    price: 95.0,
    duration: "24-48 hours",
  },
];

export const mockAdminMedications = [
  {
    id: "1",
    name: "Amoxicillin 500mg",
    company: "Pfizer",
    quantity: 500,
    price: 12.99,
    sideEffects: "Nausea, diarrhea",
  },
  {
    id: "2",
    name: "Ibuprofen 200mg",
    company: "Bayer",
    quantity: 1200,
    price: 8.49,
    sideEffects: "Stomach upset",
  },
  {
    id: "3",
    name: "Metformin 850mg",
    company: "Merck",
    quantity: 350,
    price: 15.99,
    sideEffects: "GI issues",
  },
  {
    id: "4",
    name: "Lisinopril 10mg",
    company: "Novartis",
    quantity: 800,
    price: 22.5,
    sideEffects: "Dry cough",
  },
  {
    id: "5",
    name: "Atorvastatin 20mg",
    company: "AstraZeneca",
    quantity: 600,
    price: 18.75,
    sideEffects: "Muscle pain",
  },
  {
    id: "6",
    name: "Omeprazole 20mg",
    company: "GSK",
    quantity: 950,
    price: 9.99,
    sideEffects: "Headache",
  },
  {
    id: "7",
    name: "Amlodipine 5mg",
    company: "Pfizer",
    quantity: 420,
    price: 14.25,
    sideEffects: "Swelling",
  },
  {
    id: "8",
    name: "Gabapentin 300mg",
    company: "Teva",
    quantity: 280,
    price: 28.99,
    sideEffects: "Dizziness",
  },
  {
    id: "9",
    name: "Gabapentin 300mg",
    company: "Teva",
    quantity: 280,
    price: 28.99,
    sideEffects: "Dizziness",
  },
  {
    id: "10",
    name: "Gabapentin 300mg",
    company: "Teva",
    quantity: 280,
    price: 28.99,
    sideEffects: "Dizziness",
  },
  {
    id: "11",
    name: "Gabapentin 300mg",
    company: "Teva",
    quantity: 280,
    price: 28.99,
    sideEffects: "Dizziness",
  },
  {
    id: "12",
    name: "Gabapentin 300mg",
    company: "Teva",
    quantity: 280,
    price: 28.99,
    sideEffects: "Dizziness",
  },
  {
    id: "13",
    name: "Gabapentin 300mg",
    company: "Teva",
    quantity: 280,
    price: 28.99,
    sideEffects: "Dizziness",
  },
];
